### ISSUE TITLE
updatemasternode feature

### ISSUE THREAD

**Issue by mjollnir14** [DeFiCh/ain#1001]
#### What would you like to be added:
Enabling back updatemasternode feature (disabled since 2.2.0)

#### Why is this needed:
Unable to change operatornode. Problematic for timelock nodes (5y/10y)

**Comment by prasannavl** [comment]
This is a part of https://github.com/DeFiCh/ain/milestone/10. And the work has also been long completed a while ago (https://github.com/DeFiCh/ain/pull/934). 

Unfortunately, it will not be released until the next planned larger version as that would cause disruption to many aspects of the ecosystem. Closing this, since it's a known intentional delay that will be enabled back in 3.0.
