### ISSUE TITLE
v3 Breaking API Tracker

### ISSUE THREAD

**Issue by prasannavl** [DeFiCh/ain#1105]
An issue to start tracking breaking API changes on v3. 

**Summary**

**RPC**: 

- `listcollateraltokens`: `height` and `all` will be removed.

**Comment by Bushstar** [comment]
listloantokens and getloantoken now includes a mintable field.

**Comment by Bushstar** [comment]
listcollateraltokens no longer has any arguments and will return all collateral tokens, even those pending at future heights. This is due to the fact that post-GW all collateral tokens will be live when they are added to the Gov var store, but pending collateral tokens will be visible instead by listgovs.

**Comment by hidiego** [comment]
Minor change: `createpoolpair` will now return RPC error if pairSymbol string is larger than 16 chars
Issue: #1068 
PR: #1069
