### ISSUE TITLE
Loan payback during stock split fails

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#1424]
#### What happened:

During a stocksplit the corresponding pool is deactivated and the vaults are frozen. Normally in a frozen vault you can payback the loan (to prevent liquidation after reactivation due to dropping collateral).
Paying the loan back during the stocksplit fails with message "PaybackLoanTx: Pool currently disabled due to locked token (code 16)"
I assume that the payback works, but swapping the interest to DUSD fails and therefore the whole thing fails.

#### What you expected to happen:

payback of loans should always be possible. in this case the interest should not be swapped to DUSD (cause its not possible) but be burned directly.

#### How to reproduce it (as minimally and precisely as possible):
try to payback a loan of a locked token.

**Comment by prasannavl** [comment]
Thanks for reporting this. If this is the case, definitely sounds like a bug. Trying to reproduce.

/triage accepted

**Comment by kuegi** [comment]
also depositing DUSD to a vault with TSLA loan right now is not possible 
`Test DepositToVaultTx execution failed:
Fixed interval price currently disabled due to locked token`
But this should also work right?

**Comment by prasannavl** [comment]
Hi @kuegi - Just looked at this again. Apologies for the earlier comment. It is indeed the expected scenario. 

Token lock is a global lock on tokens as an exception event. Currently, stock splits are the only feature that use it for safety. Over time, making these locks granular could be one desired approach. 

However, in the term term, I wonder if enabling DUSD for collateral deposits into vaults at all points in time is a safe alternative since that is fixed and is not subject to price changes. 

On the subject of payback, should we enable burns without DUSD and it's consequences is a different subject entirely. Or perhaps, have a special cased burn only during locked events.

**Comment by kuegi** [comment]
Thx @prasannavl for the feedback. I understand that a locked token puts a break on everything, but imho the possibility to reduce risk must be a main focus.

regarding the deposits: IMHO the oracle price of any token (no matter if its the used one or any other token in the vault) does not change the decision if a deposit is correct or not. Adding coins is always allowed, so neither should the inavailability of an oracle price change this decision.

For the payback I understand the technical reason, but again the focus should be on the possibility to reduce risk. Thats the reason why payback is allowed even when oracles are offline. So the technical reason (swap of interest to DUSD not possible) should not prevent that IMHO.

Should I make feature-request issues for both topics or better change this issue to a feature request for the payback and I create one for the deposit case?

**Comment by prasannavl** [comment]
Closing outdated / stale issues.
