### ISSUE TITLE
Consistent output for percentage values in listgovproposals

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/ain#1601]
#### What happened:
![image](https://user-images.githubusercontent.com/76614620/204021905-a82be12a-a88d-43d8-a4b8-faa6d7b6b747.png)

#### What you expected to happen:
percentage values should not be put in strings as output, 0.5 for threshold and 1.0 quorum for Consistent output and further processing facilitate

example:
http://tc01.mydefichain.com/listpoolpairs/
![image](https://user-images.githubusercontent.com/76614620/204022158-ce17512b-57fa-49a2-8c06-b3b3e5545a61.png)

#### How to reproduce it (as minimally and precisely as possible):
just check listgovproposals or online: http://tc01.mydefichain.com/listgovproposals/

#### What are your environment parameters:
ain 3.0.0 rc5 in testnet

#### Anything else we need to know?:
-

**Comment by prasannavl** [comment]
Hi @bernd-mack - this is very intentional. It's new type which is going to be suffixed with `%` which indicates a percent or a numeric string where precision is no longer susceptible to unintentional json rounding. As there are some fields which can take both percent and fixed numeric as output (eg. `v0/gov/proposals/cfp_fee`). It would be sub-optimal to have 2 fields, one called pct, and one for fixed and then unnecessarily complicate logic to arbitrate between the two, ordering, priorities, etc and then introduce further developer headaches and caveats for each field that needs it.

The larger plan is to expand these types more over time (likely when we end up redesigning a the attribute system). There's a lot of legacy unfortunately and unlike usual products, we can't just deprecate and change in one version, nor the resources to fully wait for a full redesign and do nothing else meanwhile. So we'll have to build migratory paths, older compatibility mapping - so it's going to go through slow deployment phases and eventually end up covering the whole spectrum. 

Also, further addressing "percentage values should not be put in strings as output, 0.5 for threshold and 1.0 quorum for Consistent output and further processing facilitate". 

50% is a lot more readable, and provides better intuitive sense that it is a percent value far easier than "quorum: 1" which now there needs to be further documentation **per field** to understand that it's percent. While this is a single know how per project that can be easily adapted across. So, "should not" is not a term I'd use lightly :)

**Comment by bernd-mack** [comment]
The "should not" always comes to mind when something doesn't fit the scheme or when familiar outputs suddenly look different without me being able to see the long plan directly.
But, I get it. Thanks for the explanation.
