### ISSUE TITLE
Pruning executed automatically after start of defid

### ISSUE THREAD

**Issue by bernd2022** [DeFiCh/ain#1776]
#### What happened:
After starting defid there is an info in the debug.log:
2023-02-23T10:52:40Z Pruning undo data prior 1471000, it can take a while...
2023-02-23T10:53:06Z Pruning undo data finished.

#### What you expected to happen:
Because of not setting any pruning parameter there shall be no pruning executed automatically.

#### How to reproduce it (as minimally and precisely as possible):
Just start defid, here are my parameters:
./defid -conf='/Users/bernd/Library/Application Support/Defi/defi.testnet.conf' -pid='/Users/bernd/Library/Application Support/Defi/defi.testnet.pid' -walletdir='/Users/bernd/.defi/wallets/testnet' -rpcallowip=127.0.0.1/8 -fallbackfee=0.00072 -acindex -spv -txindex

#### What are your environment parameters:
I use the current Node Version v3.2.5 and run defid on a MacBook (MacOS).

#### Anything else we need to know?:
Until today I run the Node Version v.3.2.2 in the same environment with the same parameters and no pruning has happen.

**Comment by prasannavl** [comment]
Let's keep the conversation in this thread since it has more activity: https://github.com/DeFiCh/ain/issues/1777. However, the node behaviour has always been to prune on checkpoints for DeFiChain related account data, regardless of the prune setup. This has to be improved and merged into the larger behaviour - however, it requires quite a bit of changes in the storage layer, that even though it's one of the things on the planned list, I don't expect this to change anytime soon.
