### ISSUE TITLE
evm: Miner should use gas limit instead of gas usage during block formation

### ISSUE THREAD

**Issue by shohamc1** [DeFiCh/ain#2148]
Right now the code uses gas usage, but as per Ethereum spec it should be using gas limit.

Relevant snippet: 
https://github.com/DeFiCh/ain/blob/1d5d2fd847f57590027157c6103a175a450c62f6/src/miner.cpp#L904-L919

**Comment by shohamc1** [comment]
Current implementation is correct.

**Comment by sieniven** [comment]
<img width="717" alt="Screenshot 2023-07-13 at 11 55 35 AM" src="https://github.com/DeFiCh/ain/assets/77395630/874b8449-5109-463c-9aa4-f145904af5ab">

The current implementation is correct because the miner validates the transaction with the current state of the blockchain and calculates the gas used when mining eth transactions into the block, so as to not exceed the block size limit.
