### ISSUE TITLE
4.0.1 requires GLIBC > 2.32 on aarch64

### ISSUE THREAD

**Issue by sandrich** [DeFiCh/ain#2699]
## Summary
Tried to install 4.0.1 release on my Raspberry Pi with AARCH64 architecture and get the following
```
defichain-4.0.1/bin/defid -version
defichain-4.0.1/bin/defid: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by defichain-4.0.1/bin/defid)
defichain-4.0.1/bin/defid: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by defichain-4.0.1/bin/defid)
defichain-4.0.1/bin/defid: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by defichain-4.0.1/bin/defid)
```

the following os is installed

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debia
```

And the following glibc which I thought only requires 2.29

```
apt list libc6
Listing... Done
libc6/oldstable,now 2.31-13+rpt2+rpi1+deb11u7 arm64 [installed]
libc6/oldstable,now 2.31-13+rpt2+rpi1+deb11u7 armhf [installed,automatic]
```
-

**Comment by prasannavl** [comment]
The aarch64 builds currently on latest ubuntu, which is higher.  The current supported is only Debian stable. (12). 

It may be possible to switch this to oldstable / 11 to cover larger compatibility. (But do note old stable in reaching end of life in a few months in early 2024). 

However, we wanted to start with a later toolchain set to be safe first, since this is the first time aarch64 is formally added to the build list. Should still be open to switching this to Deb 11, as long as our current dependencies and toolchains are still supported.  

We'll aim to get this on our list soon.

**Comment by sandrich** [comment]
Thanks. I will upgrade to Debian 12. Was more confused about the description not matching what was required

**Comment by prasannavl** [comment]
Closing. Outdated issues cleanup.
