### ISSUE TITLE
nodes always oom

### ISSUE THREAD

**Issue by blocknodehub** [DeFiCh/ain#2756]
Given 16Gi's available memory, nodes always oom resulting in data corruption and suspected memory leaks
<img width="1055" alt="截屏2023-12-20 10 22 49" src="https://github.com/DeFiCh/ain/assets/100512407/91cd4805-64bf-40be-9df9-697ffcff2974">

**Comment by prasannavl** [comment]
I'm going to go ahead and close this as this is not currently actionable anytime soon, as there are many instances where there will be expected spikes that require > 16GB since EVM upgrade (esp. during internal db compactions or deep index scans on occasional TXs)

32GB is the recommended, although the usual working set is much smaller. A 16GB physical memory should be fine, as long as there's atleast a swap for the rest to accommodate for the spikes.
