### ISSUE TITLE
Lock unspents when performing custom transaction RPC calls

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#346]
#### What would you like to be added:

Lock unspents when funding custom transaction RPC calls. See the following code sections:

https://github.com/DeFiCh/ain/blob/e85a9b5e62af04de8ed062bf93bf3bbb2961e99e/src/masternodes/mn_rpc.h#L67
https://github.com/DeFiCh/ain/blob/e85a9b5e62af04de8ed062bf93bf3bbb2961e99e/src/masternodes/rpc_poolpair.cpp#L346

and more...

This should simply require setting `lockUnspents` to `true` on all custom transactions that use the `fund` funcrtion.

Testing is required to ensure that this solves the issue, and does not cause further problems.

#### Why is this needed:

Locking unspents may help solve some mempool issues where a transaction conflicts in mempool over the UTXOs used to fund the transaction.

**Comment by monstrobishi** [comment]
- Make the requested change
- Test on testnet/regtest with reproducible test provided by @fuxingloh 
- Pass build to @fuxingloh to confirm fix

**Comment by fuxingloh** [comment]
The reproducible tests are created in [DeFiCh/jellyfish](https://github.com/DeFiCh/jellyfish) using jellyfish testing framework. It is similar to ain python test framework. 

#### What causes it to fail:
Running the test group all at once will always fail, but running the test individually will succeed. To remedy, @canonbrother added `container.generate(n)` in between custom tx RPC calls so that a block is generated.

I believe this should not be the case as the consumer should not need to be aware of mempool/block progress.

[test code reference](https://github.com/DeFiCh/jellyfish/blob/866abecc280a4701847187731b6c578a3b174362/packages/jellyfish-api-core/__tests__/category/poolpair.test.ts#L260-L306)

**Comment by fuxingloh** [comment]
@fuxingloh needs to generate a deterministic set for this behaviour, I will work on this when I have more availability.
