### ISSUE TITLE
Full `acindex` does not contain all account history records

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#441]
#### What happened:

Some account history records are missing from full ac index. Seems to happen more for non-DFI assets.

#### What you expected to happen:

Should contain everything.

**Comment by uzyn** [comment]
How to reproduce:

1. Sync from snapshot. Snapshot is assumed to be `acindex` + `txindex`.
2. `defi-cli listaccounthistory dHuocTKykTQUpxcaNggFsxdvyWV67udV8b` only contains `@DFI` transactions, without `@ETH`.

Here's an example that shows that the address does contain ETH token history:
https://dex.defichain.com/mainnet/tx/972be8e6303317d564ef3cce1c1f4887c870de7471e64e7b918188d5aff53599


Notes: 
1. `dHuocTKykTQUpxcaNggFsxdvyWV67udV8b` is in local `wallet.dat`.
2. This only occurs if it is synced from snapshot, if it is `-reindex` from scratch with , the history would show up.

**Comment by uzyn** [comment]
Another finding, it might be a regression of `txindex`. Addresses that are in wallet, with UTXO, does not show up under `listreceivedbyaddress`. 

@thedoublejay reported this.

**Comment by Kolibri1990** [comment]
![image](https://user-images.githubusercontent.com/66674482/120403526-a2b69800-c344-11eb-855a-e2b175253522.png)

The wallet works fine for me except the transaction history... from the block ~726k is all gone...even with -reindex and -checkpoints=0... I also wrote it yesterday here to U Zyn... the histories should be there or with that settings? I understand that now is much more important to do the hardfork everything right than to display the rewards of the LM.... but it will be important again sometime

**Comment by bvbfan** [comment]
Transaction history cannot just go away. I see you're on 733100 (so no need to specified it `maxBlockHeight` when it matches the current height) So you have transactions that aren't shown between 726876 and 733100? At chechpoint we erase undos since they are not needed, tx history is never deleted, by deleting undos we loose ability to show Rewards history. Rewards are not transactions, they act like events when it comes you receive tokens, that's not recordered as tx in the blockchain, more like event on mined new block.

**Comment by Kolibri1990** [comment]
thx @bvbfan for your response.

![image](https://user-images.githubusercontent.com/66674482/120434293-90f0e700-c37c-11eb-89e2-b98bf52276f3.png)

The history is missing since this block 728756... I am now fully synchronized and with listaccounthistory mine used to get the last 100 history entries by default.

**Comment by bvbfan** [comment]
Did you add liquidity? I don't see rewards. This output is pretty unlikely to be seen.

**Comment by bvbfan** [comment]
Did you see your txs in https://explorer.defichain.io/#/DFI/mainnet/home  ?

**Comment by Kolibri1990** [comment]
Yes I can see my last transaction a week ago since I trying to get the history back.
On my wallet is liquidity since 13th December (BTC-DFI) and later all other Pools. (Without DOGE)
DFI is increasing on my address but no history is shown:

![image](https://user-images.githubusercontent.com/66674482/120439454-d31d2700-c382-11eb-9dac-9c6ade248d14.png)

**Comment by bvbfan** [comment]
So you have some misconfiguration in defi.conf. The explorer uses the blockchain (same as you) the difference is you own the address (say you have the rights to use the money)

**Comment by uzyn** [comment]
It seems the issue is fixed now after @monstrobishi updated the snapshot to include `history/`. 

@thedoublejay has confirmed that https://github.com/DeFiCh/ain/issues/441#issuecomment-849547300 is solved.

@Kolibri1990 I think you have a different issue. You may want to open a new issue for yours. I'll leave it open for now as it seems you are having a conversation with @bvbfan and I do not want to cut you off.

**Comment by Kolibri1990** [comment]
Thanks @uzyn and @bvbfan 
I just created a new issue and updated it because I figured out, that when I try the command with one of my address the history will shown... but not with the key "mine"
-> https://github.com/DeFiCh/ain/issues/470
