### ISSUE TITLE
Correction of CLI documentation

### ISSUE THREAD

**Issue by defiprop** [DeFiCh/ain#972]
#### What would you like to be added:

Replace syntactically incorrect commands/examples by correct ones

#### Why is this needed:

It is kind of frustrating to have so many commands that are not working. It is not only a problem in the documentation in the wiki, but also within the client. Here are some examples (from [Loan-and-Decentralized-Tokenization](https://github.com/DeFiCh/ain/wiki/Loan-and-Decentralized-Tokenization)):

is:
`defi-cli createvault <ownerAddress> <vaultId> <loanSchemeId>` 
should be:
`defi-cli createvault <ownerAddress> <loanSchemeId>`

is:
`defi-cli utxostoaccount '{"<address>":"<amount(value@token)>"}'`
should be:
`defi-cli utxostoaccount {"<address>":"<amount(value@token)>"}`

is:
`defi-cli takeloan '{"vaultId":"<vaultId>", "amounts":"<amount(value@token)>"}'`
should be:
`defi-cli takeloan {"vaultId":"<vaultId>","amounts":"<amount(value@token)>"}`
(note also the missing blank in the correction. At least on Linux it is interpreted as string.) 

is:
`defi-cli paybackloan '{"vaultId":"<vaultId>", "from":"<DFI Address>","amounts":"<amount(value@token)>"}'`
should be:
`defi-cli paybackloan {"vaultId":"<vaultId>","from":"<DFI Address>","amounts":"<amount(value@token)>"}`
(note also the missing blank in the correction. At least on Linux it is interpreted as string.)

And so further ...

**Comment by prasannavl** [comment]
Thank you for reporting this. Yes, these do need to be fixed - will be tackled soon. Meanwhile, also would appreciate any help as they are easy for beginners, but go a long way to help the users.

**Comment by chrizog** [comment]
I will take a look on it as I am searching for good first issues.

**Comment by chrizog** [comment]
@defiprop I investigated the issues.

For example take:
defi-cli utxostoaccount '{"<address>":"<amount(value@token)>"}'

For me this is actually a valid command. Because the single quotes (''), put the content between the quotes as a single argument which is passed to defi-cli. With using the quotes you can even use blank spaces inside the content which makes it more readable.

The other way around your proposed:
defi-cli utxostoaccount {"<address>":"<amount(value@token)>"}
is not recognized correctly.

I assume it could be related to the shell someone uses. I am using Z shell (zsh) under macOs. What are you using?

**Comment by chrizog** [comment]
@defiprop Do you have any comment to my reply?

The wiki is already corrected and as I explained the examples on defi-cli are also correct with the single quotes. I guess if there are no more complaints, the issue can be closed.
