### ISSUE TITLE
Every loan costs minimum 0.00000001 dToken interest per block

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/ain#980]
#### What happened:
Taking a loan since the 2.3.0 update, always charges a minimum of 0.00000001 (1e-8) interest per Block. this can result in massive interests.
f.e. a loan of 0.000001 (1e-6) TSLA currently costs 1% interest PER BLOCK

Related issue: https://github.com/DeFiCh/wallet/issues/1674

**Comment by kuegi** [comment]
seems this was introduced with the 2.3.0 update, where all interestPerBlock calculations got a "ceil" around it. Leading to minimum  being 1 now.

**Comment by JayMadR** [comment]
you mean this, right?
https://twitter.com/JayMad_R/status/1468515319350243332?s=20

**Comment by kuegi** [comment]
> you mean this, right? https://twitter.com/JayMad_R/status/1468515319350243332?s=20

yes exactly.

**Comment by hidiego** [comment]
The Interest Per Block calculation was changed to support greater precision. Before interest per block was ceiled leading to a minimum of 1 per block, this was fixed in #1082 and introduced in Fort Canning Hill. Now total interest of the loan is ceiled and interest per block is added internally with sub satoshi precision.
